
version: '3.9'

services:

  redis:
    image: redis:alpine
    networks:
      - my-network

  api:
    image: my-api-image
    container_name: api
    env_file:
      - .env
    restart: always
    ports: 
      - "8000:8000"
    depends_on:
      - webhook
    networks:
      - my-network

  webhook:
    image: my-webhook-image
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network: